/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IframeAuthRouteImport } from './routes/iframe-auth'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedAiTextToolsRouteImport } from './routes/_protected/ai-text-tools'
import { Route as ProtectedAnalyticsRouteImport } from './routes/_protected/analytics'
import { Route as ProtectedBrandAssetsRouteImport } from './routes/_protected/brand-assets'
import { Route as ProtectedChangelogRouteImport } from './routes/_protected/changelog'
import { Route as ProtectedChatRouteImport } from './routes/_protected/chat'
import { Route as ProtectedConnectorsRouteImport } from './routes/_protected/connectors'
import { Route as ProtectedDocumentPipelineRouteImport } from './routes/_protected/document-pipeline'
import { Route as ProtectedExportCenterRouteImport } from './routes/_protected/export-center'
import { Route as ProtectedGalleryRouteImport } from './routes/_protected/gallery'
import { Route as ProtectedImportWizardRouteImport } from './routes/_protected/import-wizard'
import { Route as ProtectedInsightsRouteImport } from './routes/_protected/insights'
import { Route as ProtectedInventoryRouteImport } from './routes/_protected/inventory'
import { Route as ProtectedKnowledgeBaseRouteImport } from './routes/_protected/knowledge-base'
import { Route as ProtectedPromptLibraryRouteImport } from './routes/_protected/prompt-library'
import { Route as ProtectedRolesPermissionsRouteImport } from './routes/_protected/roles-permissions'
import { Route as ProtectedSavedReportsRouteImport } from './routes/_protected/saved-reports'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedStorageRouteImport } from './routes/_protected/storage'
import { Route as ProtectedSystemRouteImport } from './routes/_protected/system'
import { Route as ProtectedThemeRouteImport } from './routes/_protected/theme'
import { Route as ProtectedTodoRouteImport } from './routes/_protected/todo'
import { Route as ProtectedWorkflowsRouteImport } from './routes/_protected/workflows'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IframeAuthRoute = IframeAuthRouteImport.update({
  id: '/iframe-auth',
  path: '/iframe-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAiTextToolsRoute = ProtectedAiTextToolsRouteImport.update({
  id: '/ai-text-tools',
  path: '/ai-text-tools',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAnalyticsRoute = ProtectedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedBrandAssetsRoute = ProtectedBrandAssetsRouteImport.update({
  id: '/brand-assets',
  path: '/brand-assets',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedChangelogRoute = ProtectedChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedChatRoute = ProtectedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedConnectorsRoute = ProtectedConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDocumentPipelineRoute =
  ProtectedDocumentPipelineRouteImport.update({
    id: '/document-pipeline',
    path: '/document-pipeline',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedExportCenterRoute = ProtectedExportCenterRouteImport.update({
  id: '/export-center',
  path: '/export-center',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedGalleryRoute = ProtectedGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedImportWizardRoute = ProtectedImportWizardRouteImport.update({
  id: '/import-wizard',
  path: '/import-wizard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedInsightsRoute = ProtectedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedInventoryRoute = ProtectedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedKnowledgeBaseRoute = ProtectedKnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPromptLibraryRoute = ProtectedPromptLibraryRouteImport.update({
  id: '/prompt-library',
  path: '/prompt-library',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedRolesPermissionsRoute =
  ProtectedRolesPermissionsRouteImport.update({
    id: '/roles-permissions',
    path: '/roles-permissions',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSavedReportsRoute = ProtectedSavedReportsRouteImport.update({
  id: '/saved-reports',
  path: '/saved-reports',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedStorageRoute = ProtectedStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSystemRoute = ProtectedSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedThemeRoute = ProtectedThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTodoRoute = ProtectedTodoRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedWorkflowsRoute = ProtectedWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/iframe-auth': typeof IframeAuthRoute
  '/sign-in': typeof SignInRoute
  '/ai-text-tools': typeof ProtectedAiTextToolsRoute
  '/analytics': typeof ProtectedAnalyticsRoute
  '/brand-assets': typeof ProtectedBrandAssetsRoute
  '/changelog': typeof ProtectedChangelogRoute
  '/chat': typeof ProtectedChatRoute
  '/connectors': typeof ProtectedConnectorsRoute
  '/document-pipeline': typeof ProtectedDocumentPipelineRoute
  '/export-center': typeof ProtectedExportCenterRoute
  '/gallery': typeof ProtectedGalleryRoute
  '/import-wizard': typeof ProtectedImportWizardRoute
  '/insights': typeof ProtectedInsightsRoute
  '/inventory': typeof ProtectedInventoryRoute
  '/knowledge-base': typeof ProtectedKnowledgeBaseRoute
  '/prompt-library': typeof ProtectedPromptLibraryRoute
  '/roles-permissions': typeof ProtectedRolesPermissionsRoute
  '/saved-reports': typeof ProtectedSavedReportsRoute
  '/settings': typeof ProtectedSettingsRoute
  '/storage': typeof ProtectedStorageRoute
  '/system': typeof ProtectedSystemRoute
  '/theme': typeof ProtectedThemeRoute
  '/todo': typeof ProtectedTodoRoute
  '/workflows': typeof ProtectedWorkflowsRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/iframe-auth': typeof IframeAuthRoute
  '/sign-in': typeof SignInRoute
  '/ai-text-tools': typeof ProtectedAiTextToolsRoute
  '/analytics': typeof ProtectedAnalyticsRoute
  '/brand-assets': typeof ProtectedBrandAssetsRoute
  '/changelog': typeof ProtectedChangelogRoute
  '/chat': typeof ProtectedChatRoute
  '/connectors': typeof ProtectedConnectorsRoute
  '/document-pipeline': typeof ProtectedDocumentPipelineRoute
  '/export-center': typeof ProtectedExportCenterRoute
  '/gallery': typeof ProtectedGalleryRoute
  '/import-wizard': typeof ProtectedImportWizardRoute
  '/insights': typeof ProtectedInsightsRoute
  '/inventory': typeof ProtectedInventoryRoute
  '/knowledge-base': typeof ProtectedKnowledgeBaseRoute
  '/prompt-library': typeof ProtectedPromptLibraryRoute
  '/roles-permissions': typeof ProtectedRolesPermissionsRoute
  '/saved-reports': typeof ProtectedSavedReportsRoute
  '/settings': typeof ProtectedSettingsRoute
  '/storage': typeof ProtectedStorageRoute
  '/system': typeof ProtectedSystemRoute
  '/theme': typeof ProtectedThemeRoute
  '/todo': typeof ProtectedTodoRoute
  '/workflows': typeof ProtectedWorkflowsRoute
  '/': typeof ProtectedIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/iframe-auth': typeof IframeAuthRoute
  '/sign-in': typeof SignInRoute
  '/_protected/ai-text-tools': typeof ProtectedAiTextToolsRoute
  '/_protected/analytics': typeof ProtectedAnalyticsRoute
  '/_protected/brand-assets': typeof ProtectedBrandAssetsRoute
  '/_protected/changelog': typeof ProtectedChangelogRoute
  '/_protected/chat': typeof ProtectedChatRoute
  '/_protected/connectors': typeof ProtectedConnectorsRoute
  '/_protected/document-pipeline': typeof ProtectedDocumentPipelineRoute
  '/_protected/export-center': typeof ProtectedExportCenterRoute
  '/_protected/gallery': typeof ProtectedGalleryRoute
  '/_protected/import-wizard': typeof ProtectedImportWizardRoute
  '/_protected/insights': typeof ProtectedInsightsRoute
  '/_protected/inventory': typeof ProtectedInventoryRoute
  '/_protected/knowledge-base': typeof ProtectedKnowledgeBaseRoute
  '/_protected/prompt-library': typeof ProtectedPromptLibraryRoute
  '/_protected/roles-permissions': typeof ProtectedRolesPermissionsRoute
  '/_protected/saved-reports': typeof ProtectedSavedReportsRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_protected/storage': typeof ProtectedStorageRoute
  '/_protected/system': typeof ProtectedSystemRoute
  '/_protected/theme': typeof ProtectedThemeRoute
  '/_protected/todo': typeof ProtectedTodoRoute
  '/_protected/workflows': typeof ProtectedWorkflowsRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/iframe-auth'
    | '/sign-in'
    | '/ai-text-tools'
    | '/analytics'
    | '/brand-assets'
    | '/changelog'
    | '/chat'
    | '/connectors'
    | '/document-pipeline'
    | '/export-center'
    | '/gallery'
    | '/import-wizard'
    | '/insights'
    | '/inventory'
    | '/knowledge-base'
    | '/prompt-library'
    | '/roles-permissions'
    | '/saved-reports'
    | '/settings'
    | '/storage'
    | '/system'
    | '/theme'
    | '/todo'
    | '/workflows'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/iframe-auth'
    | '/sign-in'
    | '/ai-text-tools'
    | '/analytics'
    | '/brand-assets'
    | '/changelog'
    | '/chat'
    | '/connectors'
    | '/document-pipeline'
    | '/export-center'
    | '/gallery'
    | '/import-wizard'
    | '/insights'
    | '/inventory'
    | '/knowledge-base'
    | '/prompt-library'
    | '/roles-permissions'
    | '/saved-reports'
    | '/settings'
    | '/storage'
    | '/system'
    | '/theme'
    | '/todo'
    | '/workflows'
    | '/'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/_protected'
    | '/iframe-auth'
    | '/sign-in'
    | '/_protected/ai-text-tools'
    | '/_protected/analytics'
    | '/_protected/brand-assets'
    | '/_protected/changelog'
    | '/_protected/chat'
    | '/_protected/connectors'
    | '/_protected/document-pipeline'
    | '/_protected/export-center'
    | '/_protected/gallery'
    | '/_protected/import-wizard'
    | '/_protected/insights'
    | '/_protected/inventory'
    | '/_protected/knowledge-base'
    | '/_protected/prompt-library'
    | '/_protected/roles-permissions'
    | '/_protected/saved-reports'
    | '/_protected/settings'
    | '/_protected/storage'
    | '/_protected/system'
    | '/_protected/theme'
    | '/_protected/todo'
    | '/_protected/workflows'
    | '/_protected/'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  IframeAuthRoute: typeof IframeAuthRoute
  SignInRoute: typeof SignInRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iframe-auth': {
      id: '/iframe-auth'
      path: '/iframe-auth'
      fullPath: '/iframe-auth'
      preLoaderRoute: typeof IframeAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/ai-text-tools': {
      id: '/_protected/ai-text-tools'
      path: '/ai-text-tools'
      fullPath: '/ai-text-tools'
      preLoaderRoute: typeof ProtectedAiTextToolsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/analytics': {
      id: '/_protected/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof ProtectedAnalyticsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/brand-assets': {
      id: '/_protected/brand-assets'
      path: '/brand-assets'
      fullPath: '/brand-assets'
      preLoaderRoute: typeof ProtectedBrandAssetsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/changelog': {
      id: '/_protected/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ProtectedChangelogRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/chat': {
      id: '/_protected/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ProtectedChatRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/connectors': {
      id: '/_protected/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof ProtectedConnectorsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/document-pipeline': {
      id: '/_protected/document-pipeline'
      path: '/document-pipeline'
      fullPath: '/document-pipeline'
      preLoaderRoute: typeof ProtectedDocumentPipelineRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/export-center': {
      id: '/_protected/export-center'
      path: '/export-center'
      fullPath: '/export-center'
      preLoaderRoute: typeof ProtectedExportCenterRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/gallery': {
      id: '/_protected/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof ProtectedGalleryRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/import-wizard': {
      id: '/_protected/import-wizard'
      path: '/import-wizard'
      fullPath: '/import-wizard'
      preLoaderRoute: typeof ProtectedImportWizardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/insights': {
      id: '/_protected/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof ProtectedInsightsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/inventory': {
      id: '/_protected/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof ProtectedInventoryRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/knowledge-base': {
      id: '/_protected/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof ProtectedKnowledgeBaseRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/prompt-library': {
      id: '/_protected/prompt-library'
      path: '/prompt-library'
      fullPath: '/prompt-library'
      preLoaderRoute: typeof ProtectedPromptLibraryRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/roles-permissions': {
      id: '/_protected/roles-permissions'
      path: '/roles-permissions'
      fullPath: '/roles-permissions'
      preLoaderRoute: typeof ProtectedRolesPermissionsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/saved-reports': {
      id: '/_protected/saved-reports'
      path: '/saved-reports'
      fullPath: '/saved-reports'
      preLoaderRoute: typeof ProtectedSavedReportsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/storage': {
      id: '/_protected/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof ProtectedStorageRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/system': {
      id: '/_protected/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof ProtectedSystemRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/theme': {
      id: '/_protected/theme'
      path: '/theme'
      fullPath: '/theme'
      preLoaderRoute: typeof ProtectedThemeRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/todo': {
      id: '/_protected/todo'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof ProtectedTodoRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/workflows': {
      id: '/_protected/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof ProtectedWorkflowsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedAiTextToolsRoute: typeof ProtectedAiTextToolsRoute
  ProtectedAnalyticsRoute: typeof ProtectedAnalyticsRoute
  ProtectedBrandAssetsRoute: typeof ProtectedBrandAssetsRoute
  ProtectedChangelogRoute: typeof ProtectedChangelogRoute
  ProtectedChatRoute: typeof ProtectedChatRoute
  ProtectedConnectorsRoute: typeof ProtectedConnectorsRoute
  ProtectedDocumentPipelineRoute: typeof ProtectedDocumentPipelineRoute
  ProtectedExportCenterRoute: typeof ProtectedExportCenterRoute
  ProtectedGalleryRoute: typeof ProtectedGalleryRoute
  ProtectedImportWizardRoute: typeof ProtectedImportWizardRoute
  ProtectedInsightsRoute: typeof ProtectedInsightsRoute
  ProtectedInventoryRoute: typeof ProtectedInventoryRoute
  ProtectedKnowledgeBaseRoute: typeof ProtectedKnowledgeBaseRoute
  ProtectedPromptLibraryRoute: typeof ProtectedPromptLibraryRoute
  ProtectedRolesPermissionsRoute: typeof ProtectedRolesPermissionsRoute
  ProtectedSavedReportsRoute: typeof ProtectedSavedReportsRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedStorageRoute: typeof ProtectedStorageRoute
  ProtectedSystemRoute: typeof ProtectedSystemRoute
  ProtectedThemeRoute: typeof ProtectedThemeRoute
  ProtectedTodoRoute: typeof ProtectedTodoRoute
  ProtectedWorkflowsRoute: typeof ProtectedWorkflowsRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAiTextToolsRoute: ProtectedAiTextToolsRoute,
  ProtectedAnalyticsRoute: ProtectedAnalyticsRoute,
  ProtectedBrandAssetsRoute: ProtectedBrandAssetsRoute,
  ProtectedChangelogRoute: ProtectedChangelogRoute,
  ProtectedChatRoute: ProtectedChatRoute,
  ProtectedConnectorsRoute: ProtectedConnectorsRoute,
  ProtectedDocumentPipelineRoute: ProtectedDocumentPipelineRoute,
  ProtectedExportCenterRoute: ProtectedExportCenterRoute,
  ProtectedGalleryRoute: ProtectedGalleryRoute,
  ProtectedImportWizardRoute: ProtectedImportWizardRoute,
  ProtectedInsightsRoute: ProtectedInsightsRoute,
  ProtectedInventoryRoute: ProtectedInventoryRoute,
  ProtectedKnowledgeBaseRoute: ProtectedKnowledgeBaseRoute,
  ProtectedPromptLibraryRoute: ProtectedPromptLibraryRoute,
  ProtectedRolesPermissionsRoute: ProtectedRolesPermissionsRoute,
  ProtectedSavedReportsRoute: ProtectedSavedReportsRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedStorageRoute: ProtectedStorageRoute,
  ProtectedSystemRoute: ProtectedSystemRoute,
  ProtectedThemeRoute: ProtectedThemeRoute,
  ProtectedTodoRoute: ProtectedTodoRoute,
  ProtectedWorkflowsRoute: ProtectedWorkflowsRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  IframeAuthRoute: IframeAuthRoute,
  SignInRoute: SignInRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
